version: '3.8'

services:
  # Backend (Laravel)
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    command: >
      sh -c "php artisan migrate --seed --force && php artisan key:generate && php artisan schedule:work & php-fpm & wait"

    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./backend:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    networks:
      - backend-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:

volumes:
  mysql_data:
